// Generated by CoffeeScript 1.6.3
(function() {
  window.jobagrob = angular.module('jobagrob', ['ngResource']).config(function($routeProvider) {
    return $routeProvider.when('/login', {
      templateUrl: 'views/login/partials/login.html',
      controller: 'Login'
    }).when('/generator', {
      templateUrl: 'views/generator/partials/generator.html',
      controller: 'Generator'
    }).otherwise({
      templateUrl: 'views/main/partials/main.html',
      controller: 'Main'
    });
  });

}).call(this);
