// Generated by CoffeeScript 1.6.3
(function() {
  jobagrob.factory('signup', function($resource) {
    return $resource('http://localhost:port/api/signup', {
      port: ':8080'
    });
  });

}).call(this);
