// Generated by CoffeeScript 1.6.3
(function() {
  jobagrob.controller('Login', function($scope, signup) {
    console.log('Login View');
    $scope.signupValidate = signup.get();
    return $scope.signUp = function(user) {
      return signup.save(user);
    };
  });

}).call(this);
