// Generated by CoffeeScript 1.6.3
(function() {
  jobagrob.controller('Login', function($scope, signUpValidate) {
    console.log('Login View');
    return signUpValidate.query();
  });

}).call(this);
