// Generated by CoffeeScript 1.6.3
(function() {
  jobagrob.controller('Generator', function($scope) {
    $scope.fieldsets = [];
    $scope.addFieldset = function() {
      return $scope.fieldsets.push({
        elems: []
      });
    };
    $scope.addElem = function(templ, fieldset) {
      return fieldset.elems.push({
        template: templ
      });
    };
    $scope.removeElem = function(elems, elem) {
      return elems.splice(elems.indexOf(elem), 1);
    };
    $scope.addOption = function(elem) {
      return elem.opts.push(elem.$$selectedOption = {});
    };
    $scope.removeOption = function(opts, optn) {
      return opts.splice(opts.indexOf(optn), 1);
    };
    $scope.addRadio = function(elem) {
      return elem.radios.push({});
    };
    $scope.removeRadio = function(radios, radio) {
      return radios.splice(radios.indexOf(radio), 1);
    };
    $scope.addCheckbox = function(elem) {
      return elem.checkboxes.push({});
    };
    $scope.removeCheckbox = function(checkboxes, checkbox) {
      return checkboxes.splice(checkboxes.indexOf(checkbox), 1);
    };
    return $scope.serialize = function(f) {
      return alert(angular.toJson(f));
    };
  });

}).call(this);
