// Generated by CoffeeScript 1.6.3
(function() {
  jobagrob.controller('SignUp', function($scope, signUp) {
    console.log('Sign Up');
    $scope.template = 'signup';
    return $scope.signUp = function(user) {
      return signUp.save(user);
    };
  });

  jobagrob.controller('LogIn', function($scope, logIn) {
    console.log('Log In');
    $scope.template = 'login';
    return $scope.logIn = function(credentials) {
      return logIn.save(credentials);
    };
  });

}).call(this);
